sudo: false
language: node_js
addons:
  apt:
    update: true
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
node_js: '12'
install: echo "install happens as part of setup"
script: npm run setup
after_script: npx codecov@3
branches:
  only:
    - master
    - tjs-master
